setwd("D:/FACSIMILE/ANsCBmodel")
file1 <- "O3test1_chem_test.dat"
df1 <- read.table(file1,1,skip=1)
png(file="O3test1_chem_test.png",width=1400,height=800,res=150)
par(mar=c(4,2,4,2))
par(mfrow=c(3,4))
plot(df1$O3,type="o",xlab="sec",ylab="",col="red",main="O3",cex.main=0.8)
#plot(df1$O1D[1:end],type="o",xlab="sec",ylab="",main="O1D",cex.main=0.8)
#plot(df1$O3P[1:end],type="o",xlab="sec",ylab="",main="O3P",cex.main=0.8)
plot(df1$OH,type="o",xlab="sec",ylab="",col="red",main="OH",cex.main=0.8)
plot(df1$NO,type="o",xlab="sec",ylab="",col="red",main="NO",cex.main=0.8)
plot(df1$NO2,type="o",xlab="sec",ylab="",col="red",main="NO2",cex.main=0.8)
plot(df1$HO2,type="o",xlab="sec",ylab="",main="HO2",cex.main=0.8)
plot(df1$H2O2,type="o",xlab="sec",ylab="",main="H2O2",cex.main=0.8)
plot(df1$CH3O,type="o",xlab="sec",ylab="",main="CH3O",cex.main=0.8)
plot(df1$CH3O2,type="o",xlab="sec",ylab="",main="CH3O2",cex.main=0.8)
plot(df1$CH3OOH,type="o",xlab="sec",ylab="",main="CH3OOH",cex.main=0.8)
plot(df1$CH3NO3,type="o",xlab="sec",ylab="",col="red",main="CH3NO3",cex.main=0.8)
plot(df1$HCHO,type="o",xlab="sec",ylab="",col="red",main="HCHO",cex.main=0.8)
# plot(df$O3F,type="o")
dev.off()

file2 <- "O3test1_supp_test.dat"
df2 <- read.table(file2,1,skip=1)
png(file="O3test1_supp_test.png",width=480,height=480,res=100)
par(mar=c(4,2,4,2))
par(mfrow=c(2,2))
# plot(df2$XTIME,type="o",xlab="sec",ylab="",main="time")
plot(df2$COSZA,type="o",xlab="sec",ylab="",main="COSZA")
# plot(df2$SEC,type="o",xlab="sec",ylab="",main="SEC")
plot(df2$X.2,type="o",xlab="sec",ylab="",main="J")
dev.off()

file3 <- "O3test1_chem.dat"
df3 <- read.table(file3,1,skip=1)
png(file="O3test1_chem.png",width=1400,height=800,res=150)
par(mar=c(4,2,4,2))
par(mfrow=c(3,4))
plot(df3$O3,type="o",xlab="sec",ylab="",col="red",main="O3",cex.main=0.8)
#plot(df3$O1D[1:end],type="o",xlab="sec",ylab="",main="O1D",cex.main=0.8)
#plot(df3$O3P[1:end],type="o",xlab="sec",ylab="",main="O3P",cex.main=0.8)
plot(df3$OH,type="o",xlab="sec",ylab="",col="red",main="OH",cex.main=0.8)
plot(df3$NO,type="o",xlab="sec",ylab="",col="red",main="NO",cex.main=0.8)
plot(df3$NO2,type="o",xlab="sec",ylab="",col="red",main="NO2",cex.main=0.8)
plot(df3$HO2,type="o",xlab="sec",ylab="",main="HO2",cex.main=0.8)
plot(df3$H2O2,type="o",xlab="sec",ylab="",main="H2O2",cex.main=0.8)
plot(df3$CH3O,type="o",xlab="sec",ylab="",main="CH3O",cex.main=0.8)
plot(df3$CH3O2,type="o",xlab="sec",ylab="",main="CH3O2",cex.main=0.8)
plot(df3$CH3OOH,type="o",xlab="sec",ylab="",main="CH3OOH",cex.main=0.8)
plot(df3$CH3NO3,type="o",xlab="sec",ylab="",col="red",main="CH3NO3",cex.main=0.8)
plot(df3$HCHO,type="o",xlab="sec",ylab="",col="red",main="HCHO",cex.main=0.8)
plot(df3$O3F,type="o",xlab="sec",main="O3 flux through reaction CH4+OH",cex.main=0.8)
dev.off()

file4 <- "O3test1_supp.dat"
df4 <- read.table(file4,1,skip=1)
png(file="O3test1_supp.png",width=480,height=480,res=100)
par(mar=c(4,2,4,2))
par(mfrow=c(2,2))
# plot(df4$XTIME,type="o",xlab="sec",ylab="",main="time")
plot(df4$COSZA,type="o",xlab="sec",ylab="",main="COSZA")
# plot(df4$SEC,type="o",xlab="sec",ylab="",main="SEC")
plot(df4$X.1.,type="o",xlab="sec",ylab="",main="J")
dev.off()

file5 <- "O3test1_chem_Jmean.dat"
df5 <- read.table(file5,1,skip=1)
png(file="O3test1_chem_Jmean.png",width=1400,height=800,res=150)
par(mar=c(4,2,4,2))
par(mfrow=c(3,4))
plot(df5$O3,type="o",xlab="sec",ylab="",col="red",main="O3",cex.main=0.8)
#plot(df5$O1D[1:end],type="o",xlab="sec",ylab="",main="O1D",cex.main=0.8)
#plot(df5$O3P[1:end],type="o",xlab="sec",ylab="",main="O3P",cex.main=0.8)
plot(df5$OH,type="o",xlab="sec",ylab="",col="red",main="OH",cex.main=0.8)
plot(df5$NO,type="o",xlab="sec",ylab="",col="red",main="NO",cex.main=0.8)
plot(df5$NO2,type="o",xlab="sec",ylab="",col="red",main="NO2",cex.main=0.8)
plot(df5$HO2,type="o",xlab="sec",ylab="",main="HO2",cex.main=0.8)
plot(df5$H2O2,type="o",xlab="sec",ylab="",main="H2O2",cex.main=0.8)
plot(df5$CH3O,type="o",xlab="sec",ylab="",main="CH3O",cex.main=0.8)
plot(df5$CH3O2,type="o",xlab="sec",ylab="",main="CH3O2",cex.main=0.8)
plot(df5$CH3OOH,type="o",xlab="sec",ylab="",main="CH3OOH",cex.main=0.8)
plot(df5$CH3NO3,type="o",xlab="sec",ylab="",col="red",main="CH3NO3",cex.main=0.8)
plot(df5$HCHO,type="o",xlab="sec",ylab="",col="red",main="HCHO",cex.main=0.8)
plot(df5$O3F,type="o",xlab="sec",main="O3 flux through reaction CH4+OH",cex.main=0.8)
dev.off()

file6 <- "O3test1_supp_Jmean.dat"
df6 <- read.table(file6,1,skip=1)
png(file="O3test1_supp_Jmean.png",width=480,height=480,res=100)
par(mar=c(4,2,4,2))
par(mfrow=c(2,2))
# plot(df4$XTIME,type="o",xlab="sec",ylab="",main="time")
plot(df6$COSZA,type="o",xlab="sec",ylab="",main="COSZA")
# plot(df4$SEC,type="o",xlab="sec",ylab="",main="SEC")
plot(df6$X.1.,type="o",xlab="sec",ylab="",main="J")
dev.off()
