setwd("D:/FACSIMILE/ANsCBmodel")
file1 <- "O3test0_chem.dat"
df1 <- read.table(file1,1,skip=1)
png(file="O3test0_chem.png",width=1400,height=800,res=150)
par(mar=c(2,2,2,2))
par(mfrow=c(3,4))
plot(df1$O3[1:60],type="o",xlab="sec",ylab="",col="red",main="O3",cex.main=0.8)
#plot(df1$O1D[1:60],type="o",xlab="sec",ylab="",main="O1D",cex.main=0.8)
#plot(df1$O3P[1:60],type="o",xlab="sec",ylab="",main="O3P",cex.main=0.8)
plot(df1$OH[1:60],type="o",xlab="sec",ylab="",col="red",main="OH",cex.main=0.8)
plot(df1$NO[1:60],type="o",xlab="sec",ylab="",col="red",main="NO",cex.main=0.8)
plot(df1$NO2[1:60],type="o",xlab="sec",ylab="",col="red",main="NO2",cex.main=0.8)
plot(df1$HO2[1:60],type="o",xlab="sec",ylab="",main="HO2",cex.main=0.8)
plot(df1$H2O2[1:60],type="o",xlab="sec",ylab="",main="H2O2",cex.main=0.8)
plot(df1$CH3O[1:60],type="o",xlab="sec",ylab="",main="CH3O",cex.main=0.8)
plot(df1$CH3O2[1:60],type="o",xlab="sec",ylab="",main="CH3O2",cex.main=0.8)
plot(df1$CH3OOH[1:60],type="o",xlab="sec",ylab="",main="CH3OOH",cex.main=0.8)
plot(df1$CH3NO3,type="o",xlab="sec",ylab="",col="red",main="CH3NO3",cex.main=0.8)
plot(df1$HCHO,type="o",xlab="sec",ylab="",col="red",main="HCHO",cex.main=0.8)
# plot(df$O3F,type="o")
dev.off()

file2 <- "O3test0_supp.dat"
df2 <- read.table(file2,1,skip=1)
png(file="O3test0_supp.png")
par(mar=c(2,2,2,2))
par(mfrow=c(2,2))
plot(df2$XTIME,type="o",xlab="sec",ylab="")
plot(df2$LHA,type="o",xlab="sec",ylab="")
plot(df2$SEC,type="o",xlab="sec",ylab="")
plot(df2$J,type="o",xlab="sec",ylab="")
dev.off()

file3 <- "O3test1_chem.dat"
df3 <- read.table(file3,1,skip=1)
png(file="O3test1_chem.png",width=1400,height=800,res=150)
par(mar=c(2,2,2,2))
par(mfrow=c(3,4))
plot(df3$O3[1:60],type="o",xlab="sec",ylab="",col="red",main="O3",cex.main=0.8)
#plot(df3$O1D[1:60],type="o",xlab="sec",ylab="",main="O1D",cex.main=0.8)
#plot(df3$O3P[1:60],type="o",xlab="sec",ylab="",main="O3P",cex.main=0.8)
plot(df3$OH[1:60],type="o",xlab="sec",ylab="",col="red",main="OH",cex.main=0.8)
plot(df3$NO[1:60],type="o",xlab="sec",ylab="",col="red",main="NO",cex.main=0.8)
plot(df3$NO2[1:60],type="o",xlab="sec",ylab="",col="red",main="NO2",cex.main=0.8)
plot(df3$HO2[1:60],type="o",xlab="sec",ylab="",main="HO2",cex.main=0.8)
plot(df3$H2O2[1:60],type="o",xlab="sec",ylab="",main="H2O2",cex.main=0.8)
plot(df3$CH3O[1:60],type="o",xlab="sec",ylab="",main="CH3O",cex.main=0.8)
plot(df3$CH3O2[1:60],type="o",xlab="sec",ylab="",main="CH3O2",cex.main=0.8)
plot(df3$CH3OOH[1:60],type="o",xlab="sec",ylab="",main="CH3OOH",cex.main=0.8)
plot(df3$CH3NO3,type="o",xlab="sec",ylab="",col="red",main="CH3NO3",cex.main=0.8)
plot(df3$HCHO,type="o",xlab="sec",ylab="",col="red",main="HCHO",cex.main=0.8)
# plot(df1$O3F,type="o")
dev.off()

file4 <- "O3test1_supp.dat"
df4 <- read.table(file4,1,skip=1)
png(file="O3test1_supp.png")
par(mar=c(2,2,2,2))
par(mfrow=c(2,2))
plot(df4$XTIME,type="o",xlab="sec",ylab="")
plot(df4$LHA,type="o",xlab="sec",ylab="")
plot(df4$SEC,type="o",xlab="sec",ylab="")
plot(df4$J,type="o",xlab="sec",ylab="")
dev.off()